name: Démonstration de pipeline
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: 'Etape 1 - Initialisation'
      - run: 'Etape 2 - Récupération du code'
      - run: 'Etape 3 - Build'
      - run: 'Etape 4 - Tests'
      - run: 'Etape 5 - Packaging'
      - run: 'Etape 6 - Fin du pipeline' 
