name: Démonstration de pipeline
on: push
jobs:
  integration-continue:
    name: Démonstration CI
    runs-on: ubuntu-latest

    env:
      STEP1: "Le code vient d'être poussé sur Github"
    steps:
      - name: Etape 1 - Initialisation
        run: 
          echo 'Etape 1 - Initialisation'
          echo "STEP1=$STEP1"
      - name: Etape 2 - Récupération du code
        run: echo 'Etape 2 - Récupération du code'
      - name: Etape 3 - Build
        run: echo 'Etape 3 - Build'
      - name: Etape 4 - Tests
        run: echo 'Etape 4 - Tests'
      - name: Etape 5 - Packaging
        run: echo 'Etape 5 - Packaging'
      - name: Etape 6 - Fin du pipeline
        run: echo 'Etape 6 - Fin du pipeline'
